/// Every command the plugin exposes over the Tauri IPC.
///
/// `tauri-plugin` turns each name into an `allow-<name>` / `deny-<name>`
/// permission under `permissions/autogenerated/`, so adding a command without
/// adding it here leaves it unreachable from the frontend rather than silently
/// ungated.
const COMMANDS: &[&str] = &[
    "capabilities",
    "generate_key",
    "get_key",
    "sign",
    "delete_key",
];

fn main() {
    tauri_plugin::Builder::new(COMMANDS)
        .android_path("android")
        .ios_path("ios")
        .build();
}
